# Generated by Django 4.2 on 2023-04-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Categories')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Зоголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Зоголовок')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d/', verbose_name='Зоголовок')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Зоголовок')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Зоголовок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Зоголовок')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debate.category', verbose_name='Зоголовок')),
            ],
            options={
                'verbose_name': 'Известные женщины',
                'verbose_name_plural': 'Известные женщины',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
